DEFAULT_ROTATION_ORDER = ['Xrotation','Yrotation','Zrotation']
DEFAULT_SMOOTHING_WINDOW_SIZE = 20
LEN_QUAT = 4
LEN_ROOT_POS = 3
LEN_EULER = 3
ROTATION_TYPE_EULER = 0
ROTATION_TYPE_QUATERNION = 1
LEN_ROOT = 3