P_KEY = "position"
O_KEY = "orientation"
START_KEY = "startPose"
T_KEY = "time"
ACTIONS_KEY = "elementaryActions"
ACTION_KEY = "action"
TASKS_KEY = "tasks"
SESSION_KEY = "session"
GROUP_KEY = "groupId"
OUTPUT_MODE_KEY = "outputMode"
CONSTRAINTS_KEY = "constraints"
ANNOTATIONS_KEY = "keyframeAnnotations"
KEYFRAME_KEY = "keyframe"
KEYFRAME_CONSTRAINTS_KEY = "keyframeConstraints"
TRAJECTORY_CONSTRAINTS_KEY = "trajectoryConstraints"
ESTIMATE_ORIENTATION_KEY = "setOrientationFromTrajectory"

