NODE_TYPE_START = "start"
NODE_TYPE_STANDARD = "standard"
NODE_TYPE_END = "end"
NODE_TYPE_SINGLE = "single_primitive"
B_SPLINE_DEGREE = 3
META_INFORMATION_FILE_NAME = "meta_information.json"
TRANSITION_DEFINITION_FILE_NAME = "graph_definition.json"
TRANSITION_MODEL_FILE_ENDING = ".GPM"
