__author__ = 'erhe01'
SPATIAL_CONSTRAINT_TYPE_TRAJECTORY = "trajectory"
SPATIAL_CONSTRAINT_TYPE_KEYFRAME_POSITION = "keyframe_position"
SPATIAL_CONSTRAINT_TYPE_KEYFRAME_DIR = "keyframe_direction"
SPATIAL_CONSTRAINT_TYPE_KEYFRAME_POSE = "keyframe_pose"
SPATIAL_CONSTRAINT_TYPE_TWO_HAND_POSITION = "keyframe_two_hands"
SPATIAL_CONSTRAINT_TYPE_TRAJECTORY_SET = "trajectory_set"