__author__ = 'erhe01'
SPATIAL_CONSTRAINT_TYPE_TRAJECTORY = "trajectory"
SPATIAL_CONSTRAINT_TYPE_KEYFRAME_POSITION = "keyframe_position"
SPATIAL_CONSTRAINT_TYPE_KEYFRAME_DIR_2D = "keyframe_2d_direction"
SPATIAL_CONSTRAINT_TYPE_KEYFRAME_POSE = "keyframe_pose"
SPATIAL_CONSTRAINT_TYPE_TWO_HAND_POSITION = "keyframe_two_hands"
SPATIAL_CONSTRAINT_TYPE_TRAJECTORY_SET = "trajectory_set"
SPATIAL_CONSTRAINT_TYPE_KEYFRAME_LOOK_AT = "keyframe_look_at"
from .mgrd_constraint import MGRDKeyframeConstraint
from .trajectory_constraint import TrajectoryConstraint
from .trajectory_set_constraint import TrajectorySetConstraint
from .discrete_trajectory_constraint import DiscreteTrajectoryConstraint
from .keyframe_constraints.pose_constraint import PoseConstraint
from .keyframe_constraints.direction_2d_constraint import Direction2DConstraint
from .keyframe_constraints.global_transform_constraint import GlobalTransformConstraint
from .keyframe_constraints.pose_constraint_quat_frame import PoseConstraintQuatFrame
from .keyframe_constraints.two_hand_constraint import TwoHandConstraintSet
from .keyframe_constraints.look_at_constraint import LookAtConstraint